#+TITLE: AD57X4R
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Library Information
  - Name :: AD57X4R
  - Version :: 4.0.1
  - License :: BSD
  - URL :: https://github.com/janelia-arduino/AD57X4R
  - Author :: Peter Polidoro
  - Email :: peterpolidoro@gmail.com

  Provides an SPI based interface to the AD5724R, AD5734R, and the AD5754R Quad
  12-/14-/16-Bit Unipolar/Bipolar Voltage Output DACs.

  The outputs can be set two ways, either by setting the analog value or by
  setting the voltage directly. The analog values are integers with the range
  determined by the resolution and whether the output is set to unipolar or
  bipolar. This is similar to Arduino analogWrite and this method is provided as
  an alternative name for convenience. Alternatively, the output voltages can be
  set directly. Voltages are floats with the minimum and maximum values
  determinded by the output range. By default, the outputs are updated
  immediately after they are set, but the outputs can be updated synchronously
  by using the simultaneous update methods.

* Wiring

  | PIN       | CONNECTION                                                          |
  |-----------+---------------------------------------------------------------------|
  | SDIN      | connect to processor MOSI pin or SDO of previous daisy-chained chip |
  | SDO       | connect to processor MISO pin or SDIN of next daisy-chained chip    |
  | SCLK      | connect to processor SCK pin                                        |
  | SYNC      | connect to processor chip select pin                                |
  | BIN2SCOMP | GND                                                                 |
  | LDAC      | GND or connect to processor pin and use setLoadDacPin method        |
  | CLR       | DVCC or connect to processor pin and use setClearPin method         |
